project:
  type: website
  output-dir: docs

website:
  title: "Giancarlo Pisciotta's Blog"
  site-url: https://www.myblogexample.io
  description: "A great sample blog"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/giancarlo-pisciotta/
      - icon: twitter
        href: https://twitter.com/gcpisciotta
format:
  html:
    theme: united
    css: styles.css



