project:
  type: website
  output-dir: docs

website:
  title: "Quarto Blog"
  site-url: https://www.myblogexample.io
  description: "A great sample blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: united
    css: styles.css



